apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: ia-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          args: ["serve"]
          ports:
            - containerPort: 11434
          env:
            - name: OLLAMA_MODELS
              value: "/root/.ollama"
            - name: OLLAMA_NUM_PARALLEL
              value: "2"
            - name: OLLAMA_MAX_LOADED_MODELS
              value: "2"
            - name: OLLAMA_KEEP_ALIVE
              value: "10m"
          volumeMounts:
            - name: pvc
              mountPath: /root/.ollama
          resources:
            requests:
              memory: "8Gi"
              cpu: "4000m"
            limits:
              memory: "16Gi"
              cpu: "8000m"
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: llm-models-pvc
